### ISSUE TITLE
Add-In installation issue in ArcMap 10.8

### ISSUE THREAD

**Issue by beuan** [pcgosling/ArcGIS-ProjectionSelection#1]
@pcgosling great job on the tool and paper!
I am trying to install the tool for my ArcMap 10.8. I successfully installed the Add-In and it shows in Add-In Manager. However, it seems that the toolbar is missing GUI components. Do you perhaps know what I am missing? Thanks!

![image](https://user-images.githubusercontent.com/4515701/75378708-0708c300-5889-11ea-9cb3-026c4c81369c.png)

**Comment by pcgosling** [comment]
Thanks and sorry it isn’t working. I have just upgraded my ArcMap to 10.8 too but haven’t had time to test the tool yet. It was originally created in version 10.4 but was working fine in 10.6.1 when I posted to GitHub. I have also seen this missing GUI effect before and it is normally something simple that has gone wrong. I will take a look as soon as I can.

**Comment by pcgosling** [comment]
I have successfully tested the tool using ArcMap 10.8 so thankfully no issues!

On checking the online ESRI Help I now understand that I should probably also be sharing the .esriaddin file that I create. For some reason I thought that people I share with would have to run the makeaddin.py themselves. Therefore, I have uploaded the .esriaddin file so please give that a go and let me know if that works.

Many thanks.

**Comment by beuan** [comment]
Yes, that resolve the issue. Probably the python script did not generated the right .esriaddin file or something. Thanks!
